Added distinguish between stateful and stateless events.
CamStreamer/CamScripterApp_examples pull request #61
Opened 2022-09-05 08:34 UTC by VaclavStupka

2022-09-05 10:54 UTC, CamStreamer requested changes

2022-09-05 10:54 UTC, CamStreamer commented on GraphicsForAxisEvents/src/main.ts
>      const path = "./localdata/"; //process.env.PERSISTENT_DATA_PATH;
Tady bys mel asi mit ten zakomentovany kod?

2022-09-05 10:54 UTC, CamStreamer commented on GraphicsForAxisEvents/src/main.ts
> +    event.co.setEnabled(true);
Neni tady chyba v logice? Kdyz ti prijde state = false tak zapnes overlay?

2022-09-05 11:02 UTC, VaclavStupka commented on GraphicsForAxisEvents/src/main.ts
>      const path = "./localdata/"; //process.env.PERSISTENT_DATA_PATH;
!

2022-09-07 10:30 UTC, VaclavStupka commented on GraphicsForAxisEvents/src/main.ts
> +    event.co.setEnabled(true);
!

2022-09-07 12:42 UTC, CamStreamer approved these changes

2022-09-08 08:32 UTC, CamStreamer approved these changes

2022-09-21 10:19 UTC, closed without merging