Stupkava/lantronix
CamStreamer/CamScripterApp_examples pull request #90
Opened 2023-07-20 09:12 UTC by VaclavStupka

2023-07-20 11:58 UTC, ArtifyCZ commented on lantronixScaleReader/html/index.js
> +        $('#serviceId').val(settings.service_id);
Ain't this unnecessary?

2023-07-20 14:33 UTC, ArtifyCZ requested changes

2023-07-21 11:12 UTC, simekdan approved these changes

2023-07-24 11:04 UTC, simekdan approved these changes

2023-07-24 11:05 UTC, merged